name: Docker App Publish

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      frontend_branch:
        required: false
        type: string
        default: "main"
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "manual"
      frontend_branch:
        description: "Frontend branch"
        required: false
        default: "main"
concurrency:
  group: wisemapping-docker-${{ github.ref }}
  cancel-in-progress: false
jobs:
  docker-app-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: wise-api/target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Increase swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8
      - name: Build & Push the Full Stack Docker image
        run: |
          docker buildx build \
            --progress=plain \
            --platform linux/arm64 \
            --build-arg FRONTEND_BRANCH=${{ inputs.frontend_branch }} \
            --build-arg CACHEBUST=$(date +%s) \
            -t chaien/wisemapping:${{ inputs.tag }} \
            -t chaien/wisemapping:latest \
            -f distribution/app/Dockerfile \
            --push \
            .
